### ISSUE TITLE
how can I deploy this project?

### ISSUE THREAD

**Issue by name-trouble** [DHTMLX/gantt-docs#3]
I want to watch this docs on my local area network

**Comment by gearcoded** [comment]
@name-trouble, first, you need to install Apache and PHP (or LAMP/XAMP).
Then you need to put it to the `/var/www/html/` folder. To make it work, you will also need an additional module(`madoka`) that should be placed in the same directory as the `gantt-docs` folder:
https://files.dhtmlx.com/30d/d5d3df9e46c3b42a9c19e923ec23ed75/madoka.zip
For example:
```
/var/www/html/gantt-docs
/var/www/html/madoka
```
Then, you will need to open the following URL:
http://loaclhost/gantt-docs/index.html

**Comment by name-trouble** [comment]
> @name-trouble, first, you need to install Apache and PHP (or LAMP/XAMP). Then you need to put it to the `/var/www/html/` folder. To make it work, you will also need an additional module(`madoka`) that should be placed in the same directory as the `gantt-docs` folder: https://files.dhtmlx.com/30d/d5d3df9e46c3b42a9c19e923ec23ed75/madoka.zip For example:
> 
> ```
> /var/www/html/gantt-docs
> /var/www/html/madoka
> ```
> 
> Then, you will need to open the following URL: http://loaclhost/gantt-docs/index.html

your suggest really help me.thank you very much!
